name: Github Actions DEMO

on: [push]

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo"
        run: echo "Hello World!"

      - name: "Name"
        run: echo "I am bot! You are cheater!"

      - name: "File Show"
        run: ls -al