name: Github Actions DEMO

on: [push]

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo"
        run: echo "Hello World!"

      - name: "Environment Info"
        run: |
          uname -a
          node -v
          python --version

      - name: "File creation"
        run: |
          echo "test" > sample.txt
          ls -al